---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: ucnf-nse-ucnf-nse-service
spec:
  payload: IP
  matches:
    - match:
      route:
        - destination:
          destinationSelector:
            app: ucnf-nse-service
