---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "ucnf-client"
  replicas: 2
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "ucnf-client"
    spec:
      hostPID: true
      containers:
        - name: universal-cnf-client
          image: networkservicemesh/universal-cnf-vppagent:master
          imagePullPolicy: IfNotPresent
          env:
            - name: TRACER_ENABLED
              value: "true"
            - name: JAEGER_SERVICE_HOST
              value: jaeger.nsm-system
            - name: JAEGER_SERVICE_PORT_JAEGER
              value: "6831"
          resources:
            limits:
              networkservicemesh.io/socket: 1
          volumeMounts:
            - mountPath: /etc/universal-cnf/config.yaml
              subPath: config.yaml
              name: universal-cnf-config-volume
      volumes:
        - name: universal-cnf-config-volume
          configMap:
            name: universal-cnf-client
metadata:
  name: ucnf-client
  annotations:
    # ns.networkservicemesh.io: icmp-responder?app=icmp
    ns.networkservicemesh.io: ucnf-nse-ucnf-nse-service?app=icmp
  #   ns.networkservicemesh.io/app: icmp-responder?app=icmp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: universal-cnf-client
data:
  config.yaml: |
    initactions:
      - command:
          name: "vppctl"
          args: ["show", "version"]
      - client:
          name: "ucnf-nse-ucnf-nse-service"
          ifname: "client0"
          labels:
            app: "ucnf-client"